name: Run Weather Bot Job 2

on:
  push:
  schedule:
    - cron: '32 19 * * *'

jobs:
  run_weather_bot:
    name: Run Weather Bot Job2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.3
      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.13.0
      - name: Clean Install NPM Dependencies
        run: npm ci
      - name: Run the Bot
        run: node index.js
        env:
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN}}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN}}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID}}
